ConnectAI-E/feishu-openai

- Dockerfile
- readme.md
@Leizhenpeng I added the method of docker build
> feat: add docker build

- code/handlers/common.go
- code/handlers/group.go
- code/handlers/personal.go
- code/initialization/config.go
- code/main.go
- code/services/gpt3.go
- code/services/gpt3_test.go
- code/services/userCache.go
可指定配置文件路径(修复不是当前路径执行main.go会报错)
支持gpt-3.5-turbo模型
符合新gpt-3.5模型接口规范
> feat:支持gpt-3.5-turbo模型

- code/handlers/group.go
- code/handlers/msg.go
- code/handlers/personal.go
Remind users of how to interact with topics when opening new conversations
提醒用户打开新对话时如何与话题互动
example
> feat: better new topic card

- code/handlers/common.go
- code/handlers/msg.go
- code/handlers/personal.go
fix: code block in md  typography confusion
修复代码卡片中换行符和代码格式显示异常问题
> fix: code block in md  typography confusion

- code/go.mod
- code/go.sum
- code/handlers/group.go
- code/handlers/msg.go
- code/handlers/personal.go
- code/utils/strings.go
- code/utils/strings_test.go
> feat: add help card message

- .gitignore
- code/handlers/group.go
- code/handlers/init.go
- code/handlers/msg.go
- code/handlers/personal.go
- code/initialization/config.go
- code/initialization/lark_client.go
- code/main.go
- code/services/gpt3.go
- code/services/gpt3_test.go
> feat: env support

- .github/FUNDING.yml
- readme.md
> doc: add deployment instructions for binary installation files

- code/handlers/personal.go
Reverts Leizhenpeng/feishu-chatgpt#38
> Revert "refactor: start kill if with chain of responsibility"

- code/handlers/group.go
- code/handlers/msg.go
- code/handlers/personal.go
- code/services/gpt3.go
- code/services/gpt3_test.go
- code/services/sessionCache.go
- code/utils/strings_test.go
😎根据自然文本创建图像😎
- 基于DALL·E接口
- 模式唤醒命令，文字回复 `图片创作`或者 `/picture`
- 模式关闭同一般情况 ，文字回复清除 或者/clear
- [#49 ](https://github.com/Leizhenpeng/feishu-chatgpt/issues/49)
发送需额外开通 `获取与上传图片或文件资源`权限
具体路径：权限管理-权限配置-消息与群组-im:resource(获取与上传图片或文件资源)
最终效果
> feat: support api for DALL.E

- code/services/sessionCache.go
Modify the data structure stored in session Cache to support simultaneous storage of message queue and interactive mode
> fix: session cache meta interface error

- code/handlers/group.go
- code/handlers/init.go
- code/handlers/personal.go
- code/main.go
请简要描述此Pull Request中的更改。
- [问题编号]（问题链接）
> feat: add message read handler

- readme.md
> docs: 增加windows下serverless部署教程

- code/handlers/action.go
- code/handlers/event_action.go
- code/handlers/handler.go
- code/handlers/msg.go
- code/services/sessionCache.go
- 允许AI多次创作图片
- 允许用户自定义图片分辨率
- #49
> feat: allow custom resolution and create multiple pic

- code/main.go
- code/services/gpt3.go
- code/services/gpt3_test.go
- code/services/msgCache.go
- code/services/sessionCache.go
对 server 层代码进行了重构，包括以下方面：
- 对测试代码进行格式化和重构；
- 提取出 OpenAI 接口请求中的公共部分进行重构；
- 对 msg 缓存部分代码进行清理和重构；
- 对 session 缓存部分代码进行清理和重构。
> refactor: improve server code quality by reorganizing cache and test code

- code/config.example.yaml
- code/initialization/config.go
- code/main.go
- code/services/gpt3.go
- code/services/gpt3_test.go
- entrypoint.sh
- readme.md
支持使用自定义代理向 OpenAI API 发送请求。
#54
> feat: adding support for custom proxies

- Dockerfile
> /bin/sh: /dist/entrypoint.sh: Permission denied
修复linux下docker打包遇到的权限问题
> fix: permission denied in entrypoint.sh script

- code/handlers/handler.go
> fix: invalid picture resolution setting

- code/handlers/event_action.go
> feat: 增加语音识别结果回复

- .github/workflows/binary-release.yml
- code/handlers/common.go
修复md代码块unicode显示异常
- fix #100 
- fix #142
- fix #115
> fix: unicode characters show problem

- readme.md
> doc: optimized descrtiption about binary deployment section 

- code/handlers/handler.go
> fix: #149 raise the priority of the clear command.

- docker-compose.yaml
请简要描述此Pull Request中的更改。
- [#153]（[问题链接](https://github.com/Leizhenpeng/feishu-chatgpt/issues/153)）
> bug: fix environment invalid type

- Dockerfile
docker build 会报错 `note: module requires Go 1.18`
- [157](https://github.com/Leizhenpeng/feishu-chatgpt/issues/157)
> [fix] 修复 docker build 失败

- code/role_list.yaml
请简要描述此Pull Request中的更改。
Formatted the Markdown syntax and added 2 new roles. 
- 健康管家
- 旅游助手
- #136
> 🎨 Formatted the Markdown syntax and added 2 new roles.

- code/services/openai/billing.go
更改了余额查询的请求地址，实现了余额查询
- #185 
- #145
> [fix]解决余额查询问题

- code/go.mod
- code/go.sum
- code/handlers/card_clear_action.go
- code/handlers/card_common_action.go
- code/handlers/card_pic_action.go
- code/handlers/event_common_action.go
- code/handlers/event_pic_action.go
- code/handlers/handler.go
- code/handlers/init.go
- code/handlers/msg.go
- code/initialization/gin.go
- code/initialization/lark_client.go
- code/logger/logger.go
- code/main.go
- code/services/openai/common.go
- code/services/openai/gpt3.go
请简要描述此Pull Request中的更改。
引入 了logrus日志，方便调试，后续会优化日志开关配置
- [问题编号]（问题链接）
- #198
> 引入logrus日志

- code/handlers/event_msg_action.go
- code/handlers/msg.go
> 消息都以卡片形式回复

- code/go.mod
- code/services/openai/gpt3_test.go
- code/services/openai/stream.go
在流模式中也可以无缝兼容azure openai
https://github.com/ConnectAI-E/Feishu-OpenAI/assets/50035229/c4779e99-2aa3-4dea-96f4-b1cc8b65bf64
> feat: 流模式接口兼容Azure OpenAI

- code/handlers/msg.go
handlers/msg.go:90:2:  replace loop with aElementPool = append(aElementPool, elements...)
handlers/msg.go:113:2: replace loop with aElementPool = append(aElementPool, elements...)
handlers/msg.go:870:2:  replace loop with aElementPool = append(aElementPool, elements...)
- [问题编号]（问题链接）
> chore: slice replace loop

- code/handlers/card_pic_action.go
- code/handlers/event_pic_action.go
- code/handlers/msg.go
- code/services/openai/gpt3_test.go
- code/services/openai/picture.go
- code/services/sessionCache.go
> feat: default to dall-e-3, support more image res, add image style
